name = 'concise'
license = 'https://github.com/yingyu5658/hugo-theme-concise/blob/main/LICENSE'
licenselink = 'https://github.com/yingyu5658/hugo-theme-concise'
description = 'A concise hugo theme. Concentrate on writting.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/yingyu5658/hugo-theme-concise'

# If you have a running demo of the theme
demosite = 'https://www.yingyu5658.me'

# Taxonomy terms
tags = ['blog']
features = ["responsive"]

# If the theme has a single author
[author]
  name = 'yingyu5658'
  homepage = 'https://www.yingyu5658.me/'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    max = "0.84.2"
