name = 'concise'
license = 'GPL-3.0'
licenselink = 'https://github.com/yingyu5658/hugo-theme-concise'
description = 'A concise hugo theme. Concentrate on writting.'

# The home page of the theme, where the source can be found
homepage = ''

# If you have a running demo of the theme
demosite = 'https://github.com/yingyu5658/hugo-theme-concise/tree/main/exampleSite'

# Taxonomy terms
tags = ['blog']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'yingyu5658'
  homepage = 'https://www.yingyu5658.me/'
