baseURL = "https://www.yingyu5658.me/"
publishDir = "public"
title = "主题示例"
description = "这是一段副标题的介绍"
languageCode = "zh-CN"
theme = ["concise"]
pagination = { pagerSize = 25 }

[permalinks]
posts = ""

[params]
[[params.homepage.content]]
name = "文章归档"
url = "/post"

[[params.homepage.content]]
name = "友情链接"
url = "/links"

[[params.homepage.content]]
name = "关于"
url = "/about"

[params.footer]
content = "页脚内容"

[markup.highlight]
noClasses = true 
style = "emacs"    #github、emacs、solarized-light 等

[outputFormats.RSS]
  baseName = "atom"
